# 智能体广场 Next.js 前端：以 /agents 挂到 SvelteKit 同源入口。
FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY frontend/plaza/package.json frontend/plaza/pnpm-lock.yaml frontend/plaza/.npmrc ./
COPY frontend/plaza/src/assets/iconify-icons/bundle-icons-css.ts ./src/assets/iconify-icons/
RUN pnpm install --frozen-lockfile

COPY frontend/plaza/ ./

ARG BASEPATH=/agents
ARG NEXT_PUBLIC_BASE_PATH=/agents
ENV BASEPATH=${BASEPATH}
ENV NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}

# 数字人（讯飞 Avatar Web SDK）构建期变量：不传则为空，
# 前端 avatar.config.ts 中的 `env || 默认值` 会回退到代码内默认凭证。
ARG NEXT_PUBLIC_XF_AVATAR_SCENE_ID=
ARG NEXT_PUBLIC_XF_AVATAR_APP_ID=
ARG NEXT_PUBLIC_XF_AVATAR_API_KEY=
ARG NEXT_PUBLIC_XF_AVATAR_API_SECRET=
ARG NEXT_PUBLIC_XF_AVATAR_SERVER_URL=
ARG NEXT_PUBLIC_XF_AVATAR_ID=
ARG NEXT_PUBLIC_XF_AVATAR_VCN=
ARG NEXT_PUBLIC_XF_AVATAR_PROTOCOL=
ARG NEXT_PUBLIC_XF_AVATAR_LLM_CHANNEL=
ARG NEXT_PUBLIC_XF_ASSISTANT_ID=
ENV NEXT_PUBLIC_XF_AVATAR_SCENE_ID=${NEXT_PUBLIC_XF_AVATAR_SCENE_ID}
ENV NEXT_PUBLIC_XF_AVATAR_APP_ID=${NEXT_PUBLIC_XF_AVATAR_APP_ID}
ENV NEXT_PUBLIC_XF_AVATAR_API_KEY=${NEXT_PUBLIC_XF_AVATAR_API_KEY}
ENV NEXT_PUBLIC_XF_AVATAR_API_SECRET=${NEXT_PUBLIC_XF_AVATAR_API_SECRET}
ENV NEXT_PUBLIC_XF_AVATAR_SERVER_URL=${NEXT_PUBLIC_XF_AVATAR_SERVER_URL}
ENV NEXT_PUBLIC_XF_AVATAR_ID=${NEXT_PUBLIC_XF_AVATAR_ID}
ENV NEXT_PUBLIC_XF_AVATAR_VCN=${NEXT_PUBLIC_XF_AVATAR_VCN}
ENV NEXT_PUBLIC_XF_AVATAR_PROTOCOL=${NEXT_PUBLIC_XF_AVATAR_PROTOCOL}
ENV NEXT_PUBLIC_XF_AVATAR_LLM_CHANNEL=${NEXT_PUBLIC_XF_AVATAR_LLM_CHANNEL}
ENV NEXT_PUBLIC_XF_ASSISTANT_ID=${NEXT_PUBLIC_XF_ASSISTANT_ID}

RUN pnpm build

EXPOSE 3000
CMD ["pnpm", "start", "-H", "0.0.0.0"]
